# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[main]]
    identifier = "blog-migration-tracker"
    name       = "Migration Tracker"
    url        = "/blog-migration-tracker/"
    weight     = 50

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/HatFullOfData/"

    [social.params]
        icon = "brand-github"

