# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[main]]


[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/HatFullOfData/"

    [social.params]
        icon = "brand-github"
        newtab = true

[[social]]
    identifier = "linkedin"
    name       = "LinkedIn"
    url        = "https://www.linkedin.com/in/lauragb/"

    [social.params]
        icon = "brand-linkedin"
        newtab = true

[[social]]
    identifier = "youtube"
    name       = "YouTube"
    url        = "https://www.youtube.com/c/hatfullofdata123"

    [social.params]
        icon = "brand-youtube"
        newtab = true

[[social]]
    identifier = "MVP"
    name       = "MVP"
    url        = "https://mvp.microsoft.com/en-US/mvp/profile/a897e9c7-2510-ea11-a811-000d3a8ccaf5"

    [social.params]
        icon = "MVP"
        newtab = true

